export const string = {
  shopease: 'ShopEase',
  welcome_back: 'Welcome Back',
  sign_in_to_explore_exclusive_deals_and_manage_your_orders:
    'Sign in to explore exclusive deals and manage your orders',
  or_sign_in_with: 'Or sign in with',
  google: 'Google',
  facebook: 'Facebook',
  do_not_have_an_account: "Don't have an account?",
  sign_up: 'Sign Up',
  create_account: 'Create Account',
  join_us_to_shop_and_enjoy_exclusive_offers:
    'Join us to shop and enjoy exclusive offers',
  upload_profile_picture: 'Upload Profile Picture',
  first_name: 'First Name',
  enter_first_name: 'Enter your first name',
  last_name: 'Last Name',
  enter_last_name: 'Enter your last name',
  gender: 'Gender',
  select_gender: 'Select Gender',
  male: 'Male',
  female: 'Female',
  other: 'Other',
  email_address: 'Email Address',
  enter_email: 'Enter your email',
  password: 'Password',
  enter_password: 'Enter your password',
  confirm_password: 'Confirm Password',
  confirm_your_password: 'Confirm your password',
  create_account_btn: 'Create Account',
  or_sign_up_with: 'Or sign up with',
  already_have_an_account: 'Already have an account?',
  sign_in: 'Sign In',
  upload_profile_picture_accessibility: 'Upload profile picture',
  first_name_input_accessibility: 'First name input',
  last_name_input_accessibility: 'Last name input',
  gender_selector_accessibility: 'Gender selector',
  email_input_accessibility: 'Email input',
  password_input_accessibility: 'Password input',
  confirm_password_input_accessibility: 'Confirm password input',
  sign_up_with_google: 'Sign up with Google',
  sign_up_with_facebook: 'Sign up with Facebook',
  navigate_to_login_screen: 'Navigate to login screen',
};
